### ISSUE TITLE
This dist should not be named *Conflicts

### ISSUE THREAD

**Issue by karenetheridge** [doy/dist-checkconflicts#5]
CPAN::Meta::Spec now has the concept of a 'conflicts' prereq entry, which joyously (/s) turns out to be totally different than what this dist does.  For an example of the facepalm-worthy mishaps that can happen because of this misunderstanding, check out https://rt.cpan.org/Ticket/Display.html?id=87123.

I would highly recommend renaming this to Dist::CheckBreaks, to disambiguate from the 'conflicts' meaning in metadata (and also the [Conflicts] dzil plugin now creates metadata called x_breaks, not x_conflicts).

If you're amenable to that, I'll provide a PR. just say yay/nay!

**Comment by karenetheridge** [comment]
(there'd actually be two parallel sets of changes - one to deprecate the existing dist, and another to be applied to a new clone of the dist, to change the name.)

**Comment by doy** [comment]
Yeah, this sounds fine to me. I don't think there's really any reason to split this into two dists though - the deprecated module with the old name can just live in the same dist. I can rename the repository once you provide the pull request.

**Comment by karenetheridge** [comment]
On Mon, Aug 05, 2013 at 08:03:44AM -0700, Jesse Luehrs wrote:

> Yeah, this sounds fine to me. I don't think there's really any reason to split this into two dists though - the deprecated module with the old name can just live in the same dist. I can rename the repository once you provide the pull request.

Yep, good point, I was having brain farts on 'new module' vs 'new dist'. :)

**Comment by doy** [comment]
Any updates on this?

**Comment by karenetheridge** [comment]
I'm now leaning towards "meh", since putting this information into a module rather than metadata now seems like the wrong path to me.

**Comment by karenetheridge** [comment]
BTW there are now two related modules up -- Dist::Zilla::Plugin::Breaks and Dist::Zilla::Plugin::Test::CheckBreaks.

**Comment by doy** [comment]
Until all CPAN clients start installing MYMETA.json files when they install modules, and until there is an easy solution for locating those files, a module is really the only solution (since things like `moose_outdated` would be impossible otherwise). Is this the case yet?

**Comment by karenetheridge** [comment]
cpanm installs those, but not in a nicely agnostic searchable way. I think extending this concept is on the agenda for the QA Hackathon in Lyon, and certainly the more general problem of finding breakages (which is why I wrote the plugins to do more with x_breaks).  Will keep you posted.

@dagolden (since you were a major participant in this discussion)
