### ISSUE TITLE
Dependency on Module::Runtime is missing version

### ISSUE THREAD

**Issue by nnutter** [doy/dist-checkconflicts#6]
Module::Runtime did not get `module_notional_filename` until [v0.009](https://metacpan.org/changes/distribution/Module-Runtime) but since the version of Module::Runtime is not specified this can result in Dist::CheckConflicts failing to install.  I encountered this when trying to create a Ubuntu Lucid package which has `libmodule-runtime-perl` but is only v0.005.

**Comment by doy** [comment]
Fixed in 0.10.
