### ISSUE TITLE
exports should be installed as methods

### ISSUE THREAD

**Issue by karenetheridge** [doy/dist-checkconflicts#7]
It would be helpful if the exported subs (conflicts, check_conflicts,
calculate_conflicts, dist) were exported as methods so the ::Conflicts module
didn't need to be excluded in Test::CleanNamespaces tests.

This can be done easily with Sub::Exporter::ForMethods, or manually in
Exporter's import sub by wrapping the sub with a Sub::Name::subname() and
calling export_to_level manually.

**Comment by doy** [comment]
I'm not particularly interested in adding a dependency for this (and I don't think it can be done without adding a dependency).

**Comment by karenetheridge** [comment]
probably not without a lot of complication, anyway.
